# Generated by Django 4.2.5 on 2023-09-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
            ],
        ),
    ]
